# 简单的文件配置脚本
file(read ${INPUT_FILE} CONTENT)
string(REPLACE "@PROJECT_NAME@" "${PROJECT_NAME}" CONTENT "${CONTENT}")
string(REPLACE "@PROJECT_VERSION@" "${PROJECT_VERSION}" CONTENT "${CONTENT}")
string(REPLACE "@BUILD_DATE@" "${BUILD_DATE}" CONTENT "${CONTENT}")
string(REPLACE "@EXECUTABLE_SUFFIX@" "${EXECUTABLE_SUFFIX}" CONTENT "${CONTENT}")
file(WRITE ${OUTPUT_FILE} "${CONTENT}")
